server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: http://localhost:8080
          predicates:
            - Path=/cliente/**,/viaje/**
        - id: ticket-service
          uri: http://localhost:8081
          predicates:
            - Path=/ticket/**
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true